// Salvar em: backend/src/server.js
const express = require('express');
const formidable = require('formidable');
const app = express();
app.use(express.json());
app.use(formidable());
app.use('/api/auth', require('./routes/auth'));
app.use('/api/users', require('./routes/users'));
app.use('/api/appointments', require('./routes/appointments'));
app.use('/api/payments', require('./routes/payments'));
app.use('/api/stock', require('./routes/stock'));
app.use('/api/maintenance', require('./routes/maintenance'));
app.use('/api/patients', require('./routes/patients'));
app.use('/api/odontogram', require('./routes/odontogram'));
app.use('/api/chat', require('./routes/chat'));
app.use('/api/marketing', require('./routes/marketing'));
app.use('/api/visitor', require('./routes/visitor'));
app.use('/api/survey', require('./routes/survey'));
app.use('/api/reports', require('./routes/reports'));
app.listen(3000, () => console.log('Servidor rodando na porta 3000'));
